version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "fornecedores"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - docker-network
    restart: always

  fornecedor-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fornecedor-api
    image: wesleyeduardodev/fornecedor-api:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: test
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge