version: '3'

services:
  postgres-db:
    container_name: postgres-db-fornecedores
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "fornecedores"
      TZ: "America/Sao_Paulo"
    ports:
      - "5433:5432"
    volumes:
      -  ./postgres-data:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge