version: '3'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'fornecedores'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - docker-network
    restart: always

  fornecedores-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fornecedores-api
    image: wesleyeduardodev/fornecedores-api:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: test
      TZ: "America/Sao_Paulo"
    ports:
      - "81:3000"
    depends_on:
      - mysql-db
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge