version: '3.3'
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'fornecedores'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge