server:
  port: ${SERVER_PORT}

spring:
  application:
    name: "fornecedor-api"

  config:
    activate:
      on-profile:
        - test

  datasource:
    url: jdbc:postgresql://postgres-db:5432/fornecedores?currentSchema=public
    username: "postgres"
    password: "root"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    operations-sorter: method
    path: "/fornecedor-api/swagger-ui.html"
