server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fornecedores
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#fornecedor:
#  api:
 #   user: admin
  #  password: admin

springdoc:
  swagger-ui:
    operations-sorter: method
    path: "/fornecedor-api/swagger-ui.html"
