server:
  port: ${SERVER_PORT}

spring:
  application:
    name: "fornecedores-api"

  config:
    activate:
      on-profile:
        - test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    url: jdbc:mysql://mysql-db:3306/fornecedores?currentSchema=public
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    operations-sorter: method
    path: "/fornecedores-api/swagger-ui.html"
