server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    url: jdbc:mysql://localhost:3306/fornecedores
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


  #fornecedor:
#  api:
 #   user: admin
  #  password: admin

springdoc:
  swagger-ui:
    operations-sorter: method
    path: "/fornecedor-api/swagger-ui.html"
